apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-devops
  labels:
    app: docker-devops
spec:
  replicas: 3 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: docker-devops
  template:
    metadata:
      labels:
        app: docker-devops
    spec:
      containers:
        - name: docker-devops-container
          image: master099/DevOpsPy:release # Use the appropriate image tag
          ports:
            - containerPort: 5000 # Adjust the port as needed
---
apiVersion: v1
kind: Service
metadata:
  name: docker-devops-service
spec:
  selector:
    app: docker-devops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 # Adjust the target port to match the container port
  type: LoadBalancer # Adjust the service type based on your requirements
